# Metadata
author: Vincenzo Romano
title: Menu
subtitle: Da Michele Baden-Baden
description: >-
  Documentation for Sublime Merge and Sublime Text
lang: en
version: 0.20210512.0
date: 2021-05-12
license: >-
  Copyright © 2021 Ristorante Da Michele, Baden-Baden. All rights reserved.

output:
  - pdf
output.pdf: da-michele.en.pdf
output.base_path: 'docs/'

resources.base_path.images: 'img/'

crowbook.markdown.superscript: true

rendering.num_depth: 4
rendering.initials: false
rendering.inline_toc: true
rendering.chapter.template: "{{{number}}}. {{{chapter_title}}}"
rendering.chapter.roman_numerals: false
rendering.part.reset_counter: true
rendering.highlight: syntect
# rendering.highlight.theme: Solarized (light)

# tex.command: pdflatex
tex.class: book
tex.links_as_footnotes: true
tex.paper.size: letterpaper
tex.highlight.theme: Solarized (light)
tex.template: 'templates/latex/template.tex'

+ docs/README.md
-- ../website/menu.md
-- ../website/en/menu.md
