# Metadata
author: Vincenzo Romano
title: Menu
subtitle: Da Michele Baden-Baden
description: >-
  Tageskarte von heute
lang: de
version: 0.20210519.0
date: 2021-05-19
license: >-
  Copyright © 2021 Ristorante Da Michele, Baden-Baden. All rights reserved.

output:
  - pdf
output.pdf: da-michele_menu.pdf
output.base_path: '../../docs/'

resources.base_path.images: 'img/'

crowbook.markdown.superscript: true

rendering.num_depth: 4
rendering.initials: false
rendering.inline_toc: false
rendering.chapter.template: "{{{number}}}. {{{chapter_title}}}"
rendering.chapter.roman_numerals: false
rendering.part.reset_counter: true
rendering.highlight: syntect
# rendering.highlight.theme: Solarized (light)

# tex.command: pdflatex
tex.class: article
tex.links_as_footnotes: false
tex.paper.size: a4paper
tex.highlight.theme: Solarized (light)
tex.template: 'templates/latex/template.tex'

- docs/README.md
