name: continuous-deployment-website

on:
  push:
    branches:
      - master
    paths:
      - 'packages/website/**'

jobs:

  deploy-website:
    runs-on: ubuntu-18.04
    steps:
      # Compare https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # Compare `scripts.build` in
      # https://github.com/da-michele/da-michele.com/blob/master/packages/website/package.json
      - name: Build website
        run: |
          cd packages/website
          yarn build
      # Compare https://github.com/peaceiris/actions-gh-pages
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: da-michele.com
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy:'
