name: label-issues-reopened
author: Vincenzo Romano
description: >-
  Apply a reopened label to reopened issues.
branding:
  icon: 'refresh-ccw'
  color: 'green'

on:
  issues:
    types: reopened

jobs:

  label-issues-reopened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: reopened']
            })
